name: Minify JSON

on:
  push:
    paths:
      - "**/*.json"

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Minify all JSON files
        run: |
          for file in $(find . -type f -name "*.json"); do
            # Skip already minified files
            if [[ "$file" != *.min.json ]]; then
              jq -c . "$file" > "${file%.json}.min.json"
              echo "Generated ${file%.json}.min.json"
            fi
          done

      - name: Commit minified JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add **/*.min.json
          git diff --staged --quiet || git commit -m "Auto-update minified JSON"
          git push
